/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package io.github.hieudoanm.micro.core.banking.avro;

@org.apache.avro.specific.AvroGenerated
public enum TransactionType implements org.apache.avro.generic.GenericEnumSymbol<TransactionType> {
  DEPOSIT,
  WITHDRAWAL,
  TRANSFER;
  public static final org.apache.avro.Schema SCHEMA$ =
      new org.apache.avro.Schema.Parser()
          .parse(
              "{\"type\":\"enum\",\"name\":\"TransactionType\",\"namespace\":\"io.github.hieudoanm.micro.core.banking.avro\",\"symbols\":[\"DEPOSIT\",\"WITHDRAWAL\",\"TRANSFER\"]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }
}
