spring:
  application:
    name: "micro-core-banking"
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_core_banking
    username: micro_core_banking
    password: micro_core_banking
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: micro_core_banking
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: micro_core_banking
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: micro-core-banking
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO
    org.springframework: INFO
    io.github.hieudoanm.micro.core.banking: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always