name: Continuous Integration

on:
  push:
    branches:
      - "master"       # Main production branch
      - "develop"      # Development branch
      - "hotfix/**"    # Hotfix branches
      - "feature/**"   # Feature branches
      - "renovate/**"  # Renovate bot branches
      - "dependabot/**" # Dependabot branches
  pull_request:

jobs:
  ci:
    name: Java CI
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v5

      # Step 2: Setup Java 21 (installed via Homebrew)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Verify Gradle wrapper
      - name: Verify Gradle Wrapper
        run: ./gradlew wrapper --gradle-version

      # Step 5: Build and run tests
      - name: Build and Test
        run: ./gradlew clean build test --info

      # Step 6: Run Checkstyle
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      # Step 7: Run PMD
      - name: Run PMD
        run: ./gradlew pmdMain pmdTest
